/* Generated By:JavaCC: Do not edit this line. XPathParserConstants.java */
package org.apache.commons.jxpath.ri.parser;

public interface XPathParserConstants {

  int EOF = 0;
  int S = 1;
  int SLASH = 2;
  int SLASHSLASH = 3;
  int UNION = 4;
  int PLUS = 5;
  int MINUS = 6;
  int EQ = 7;
  int NEQ = 8;
  int LT = 9;
  int LTE = 10;
  int GT = 11;
  int GTE = 12;
  int VARIABLE = 13;
  int Literal = 14;
  int Digit = 15;
  int Number = 16;
  int Letter = 17;
  int BaseChar = 18;
  int Ideographic = 19;
  int CombiningChar = 20;
  int UnicodeDigit = 21;
  int Extender = 22;
  int OR = 23;
  int AND = 24;
  int MOD = 25;
  int DIV = 26;
  int NODE = 27;
  int TEXT = 28;
  int COMMENT = 29;
  int PI = 30;
  int AXIS_SELF = 31;
  int AXIS_CHILD = 32;
  int AXIS_PARENT = 33;
  int AXIS_ANCESTOR = 34;
  int AXIS_ATTRIBUTE = 35;
  int AXIS_NAMESPACE = 36;
  int AXIS_PRECEDING = 37;
  int AXIS_FOLLOWING = 38;
  int AXIS_DESCENDANT = 39;
  int AXIS_ANCESTOR_OR_SELF = 40;
  int AXIS_FOLLOWING_SIBLING = 41;
  int AXIS_PRECEDING_SIBLING = 42;
  int AXIS_DESCENDANT_OR_SELF = 43;
  int FUNCTION_LAST = 44;
  int FUNCTION_POSITION = 45;
  int FUNCTION_COUNT = 46;
  int FUNCTION_ID = 47;
  int FUNCTION_LOCAL_NAME = 48;
  int FUNCTION_NAMESPACE_URI = 49;
  int FUNCTION_NAME = 50;
  int FUNCTION_STRING = 51;
  int FUNCTION_CONCAT = 52;
  int FUNCTION_STARTS_WITH = 53;
  int FUNCTION_CONTAINS = 54;
  int FUNCTION_SUBSTRING_BEFORE = 55;
  int FUNCTION_SUBSTRING_AFTER = 56;
  int FUNCTION_SUBSTRING = 57;
  int FUNCTION_STRING_LENGTH = 58;
  int FUNCTION_NORMALIZE_SPACE = 59;
  int FUNCTION_TRANSLATE = 60;
  int FUNCTION_BOOLEAN = 61;
  int FUNCTION_NOT = 62;
  int FUNCTION_TRUE = 63;
  int FUNCTION_FALSE = 64;
  int FUNCTION_NULL = 65;
  int FUNCTION_LANG = 66;
  int FUNCTION_NUMBER = 67;
  int FUNCTION_SUM = 68;
  int FUNCTION_FLOOR = 69;
  int FUNCTION_CEILING = 70;
  int FUNCTION_ROUND = 71;
  int NCName = 72;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<S>",
    "\"/\"",
    "\"//\"",
    "\"|\"",
    "\"+\"",
    "\"-\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"$\"",
    "<Literal>",
    "<Digit>",
    "<Number>",
    "<Letter>",
    "<BaseChar>",
    "<Ideographic>",
    "<CombiningChar>",
    "<UnicodeDigit>",
    "<Extender>",
    "\"or\"",
    "\"and\"",
    "\"mod\"",
    "\"div\"",
    "\"node\"",
    "\"text\"",
    "\"comment\"",
    "\"processing-instruction\"",
    "\"self::\"",
    "\"child::\"",
    "\"parent::\"",
    "\"ancestor::\"",
    "\"attribute::\"",
    "\"namespace::\"",
    "\"preceding::\"",
    "\"following::\"",
    "\"descendant::\"",
    "\"ancestor-or-self::\"",
    "\"following-sibling::\"",
    "\"preceding-sibling::\"",
    "\"descendant-or-self::\"",
    "\"last\"",
    "\"position\"",
    "\"count\"",
    "\"id\"",
    "\"local-name\"",
    "\"namespace-uri\"",
    "\"name\"",
    "\"string\"",
    "\"concat\"",
    "\"starts-with\"",
    "\"contains\"",
    "\"substring-before\"",
    "\"substring-after\"",
    "\"substring\"",
    "\"string-length\"",
    "\"normalize-space\"",
    "\"translate\"",
    "\"boolean\"",
    "\"not\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"lang\"",
    "\"number\"",
    "\"sum\"",
    "\"floor\"",
    "\"ceiling\"",
    "\"round\"",
    "<NCName>",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\"..\"",
    "\"[\"",
    "\"]\"",
    "\"@\"",
    "\",\"",
    "\"*\"",
  };

}
